version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  icon: secure-lock-kubernetes.svg
  required:
    - build
    - repo
  info:
    git url: >
      "[" + $env.repository + "]" +
        "(" + $env.repository + ")"
    git branch: >
      "[" + $env.branch + "]" +
        "(" + $env.repository +
          "/tree/" + $env.branch + ")"
toolchain:
  name: 'key-setup-{{timestamp}}'
services:
  repo:
    service_id: githubpublic
    parameters:
      repo_name: '{{toolchain.name}}'
      source_repo_url: 'https://github.com/padraic-edwards/tekton-key-management-pipeline'
      type: clone
      has_issues: false
      enable_traceability: true
  build:
    service_id: pipeline
    parameters:
      name: '{{services.repo.parameters.repo_name}}'
      ui-pipeline: true
      type: tekton
      configuration:
        content:
          $text: tekton.yaml
        env:
          APP_NAME: '{{form.pipeline.parameters.app-name}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          BUILD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
          BUILD_RESOURCE_GROUP: '{{form.pipeline.parameters.prod-resource-group}}'
          VAULT_INSTANCE: '{{form.pipeline.parameters.vault_name}}'
          BUILD_SIGNER: '{{form.pipeline.parameters.build_signer}}'
          VALIDATION_SIGNER: '{{form.pipeline.parameters.validation_signer}}'
          REGISTRY_NAMESPACE: '{{form.pipeline.parameters.registry-namespace}}'
          REPOSITORY: 'https://github.com/padraic-edwards/tekton-key-management-pipeline'
          REVISION: master
          GIT_REPO: repo
        execute: true
form:
  pipeline:
    parameters:
      app-name: '{{toolchain.name}}'
      vault_name: ''
      build_signer: 'devops-build'
      validation_signer: 'devops-validation'
    schema:
      $ref: deploy.json
